version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "yarn"
    directory: "examples/react/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "yarn"
    directory: "examples/single-spa/root/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "yarn"
    directory: "examples/typescript/"
    schedule:
      interval: "weekly"
