version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/cdn/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/react-16.9/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
  - package-ecosystem: "npm"
    directory: "examples/single-spa/root/"
    schedule:
      interval: "daily"
