language: node_js
os: linux
dist: xenial
node: lts/*
notifications:
  email: false
matrix:
  include:
    - env: TARGET=examples/react-16.9
before_install:
  - "npm install -g npm@latest"
  - "cd $TARGET"

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#npm-ci-support
install: "npm ci"

script: "npm test"
after_script: "cd .."
