language: node_js
os: linux
dist: xenial
notifications:
  email: false
node_js:
  - 10.24.1
  - 12.17.0
env:
  - REACT_VERSION=16.9
  - REACT_VERSION=16.12
  - REACT_VERSION=16.13.1
before_install:
  - "cd $TRAVIS_BUILD_DIR/examples/react"
install:
  - "npm ci"
  - "npm install react@$REACT_VERSION react-dom@$REACT_VERSION"
script:
  - "npm test"
after_script:
  - "cd $TRAVIS_BUILD_DIR"
